---
title: "Package Development in 20 Minutes"
author: "Heather Lendway"
output: 
  prettydoc::html_pretty:
    highlight: vignette
    theme: cayman
    number_sections: no
  bookdown::tufte_html2:
    number_sections: no
    split_by: none
    toc: no
  bookdown::html_document2:
    number_sections: no
    split_by: none
    toc: yes
    toc_float:
      collapsed: yes
  rmarkdown::html_document:
    highlight: espresso
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

0. **Why are we interested in package development?**
    + Read Hadley's intro to R Packages [http://r-pkgs.had.co.nz/intro.html](http://r-pkgs.had.co.nz/intro.html)
    + Easily share code with others, easy to download and install
    + More organized development with standards in place which saves you times
    + Your work is well documented so that someone else can understand what you're doing
    + Automated testing so errors can quickly be debugged and fixed, great for when changes need to be made

1. **What should I name my package?** 
    + Read the "Naming your package" section - [http://r-pkgs.had.co.nz/package.html](http://r-pkgs.had.co.nz/package.html)
    + Name can consist of letters, numbers and period (recommend against using periods though)
    + Pick a unique name you could easily google and validate the name is not already in use
        + Fill in "PACKAGE_NAME" - [http://cran.r-project.org/web/packages/[PACKAGE_NAME](http://cran.r-project.org/web/packages/[PACKAGE_NAME])
    + Avoid using upper and lower, harder to remember hEaThErSpAcKaGe vs. heatherspackage
    + Find a word that describes the problem you're solving and use abbreviations, i.e. mltools
    + Add an extra R, i.e. stringr, sparklyr, dplyr, tidyr

2. **Create a new project in RStudio**
    + Click File -> New Project -> New Directory -> R Package
        + Enter the name of your package and select the directory where the project will live (wherever you typicaly store code locally)
    + Alternatively if you want to create a project based on an existing git repo you can do the following (it may take a few minutes for security to replicate down)
        + File -> New Project -> Version Control -> Git
        + For the repository URL, paste the link that was copied from github, i.e. git@github.com:hlendway/RHeather.git
            + You can find this url on the repo page, i.e. [https://github.com/hlendway/RHeather](https://github.com/hlendway/RHeather), click "Clone or Download", select use SSH and copy the string to clipboard
        + The project directory name should auto populate when the above link is pasted
        + For create project as subdirectory of, browse out to the location where you store your local repos, this is where your local repo will be stored for the new repo/project/package you're creating
        + Next if you're creating a brand new package from scratch you can run, usethis::create_package("C:/Users/YOURID/WHEREYOUSTOREYOURCODE/packagenamer") 
        + This is creating the package in the repo location, you will see all the package components are automatically created for you
      
3. **Here are a few packages you'll want installed as you're developing your own package** 
    + (this is taken from [http://r-pkgs.had.co.nz/intro.html](http://r-pkgs.had.co.nz/intro.html) - getting started)
    + install.packages(c("devtools", "roxygen2", "testthat", "knitr","usethis","rstudioapi"))
    + devtools::install_github("r-lib/devtools")
  		
4. **Package folder detail**
    + You can read about each file/folder that is setup here in detail - [http://r-pkgs.had.co.nz/](http://r-pkgs.had.co.nz/)
    + **R/** - where your code goes, each main function will be in its own script file
    + **DESCRIPTION** - package metadata, this is where you would specify any package dependencies
    + **man/** - This is what feeds the R documentation, it's generated from your roxygen comments when you run devtools::document() - see more below
    + **tests/** - where your test scripts are stored, each function
    + **NAMESPACE** - generated by roxygen, exports your functions to make them publicly available (vs. helper functions that may be private)
    + **data/** - where any data you want available in your package is stored - think [https://github.com/tidyverse/ggplot2/tree/master/data](ggplot2)
    + **src/** - compiled code
    + **Also recommend going out to github and looking at one of your favorite packages.  You can see in detail what goes into each folder/file and it's something you're familiar with** [https://github.com/tidyverse/tidyr](https://github.com/tidyverse/tidyr)
		
5. **Testing your package** 
    + Write your test cases first! Then your function.  Each function will have a .R file in /R and a test-function_name.R file in /tests/testthat
    + Function names should be verbs, describing the action that is happening
        + If you have a set of functions, use a common prefix, i.e. str_sub, str_detect
        + Give it an informative name - avoid words with dual meanings 
        + Avoid names that are used in base R
    + Run usethis::use_test("function_name")
    + There are many test case functions available - review testthat
		
6. **Create your functions** 
    + Plan for pipe-ability - i.e. your data argument should be first then any subsequent args.
    + Do not use loops or any of the apply family of functions, use the map family. Play nice with the tidyverse
    + usethis::use_r("function_name")
		 
7. **Load package and run tests**
    + Note you may need to install rtools if you have not done so, instructions here: [https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows](https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows)
    + Ctrl+shift+L -> loads your package in a package environment, not your global environment
    + Ctrl+shift+T -> runs all your tests
    
8. **Documentation**
    + You can add an ROxygen2 skeleton for a function by placing your cursor inside the function then pressing ctr+alt+shift+R
    + Generate documentation from your roxgyen snippets - ctrl+shift+d or devtools::document()

9. **Add a data set to your package**
    + If you don't have a data folder, in the file browser, add a new folder called "data"
    + Read in the data set you want to save in the package or create the data set and store it in a local object
    + Simply run devtools::use_data(your_dataset_name) and it will be added to the data folder and available when the package is loaded.
    
10. **Install your package and restart**
    + Use the shortcut ctrl+shift+b
    
11. **Next steps**
    + Deploy your package to github, push your package to github
    + install_github("hlendway/packagename")